#nginx配置
[run]
ports=17170,17171

#目录配置
[path]
webkit_node_path={PKG_PATH}/p_node
#这三个可以动态的固定目录
webkit_driver_path={DRIVE}:/devtool/webkit_driver
webkit_data_path={DRIVE}:/devtool/webkit_data
webkit_download_path={DRIVE}:/devtool/webkit_download

[base]
#如果不设置那么默认为config/{AppName}
dbPath=
#如果不设置 那么会优先查找config/{AppName}/{AppName}.db 如果不存在那么将会初始化一个config/{AppName}/{AppName}.db并初始化相关表
#如果设置 那么将会使用config/{AppName}/{dbFileName}.db
dbFileName=frog.db
#前端项目dist所在目录
#如果不填那么默认为当前golang项目同级别的devtool/dist目录
webPath=D:/go/devtool/dist