#nginx閰嶇疆
[run]
ports=17170,17171

#鐩綍閰嶇疆
[path]
#杩欎笁涓彲浠ュ姩鎬佺殑鍥哄畾鐩綍
webkit_driver_path={DRIVE}:/devtool/webkit_driver
webkit_data_path={DRIVE}:/devtool/webkit_data
webkit_download_path={DRIVE}:/devtool/webkit_download

[base]
#濡傛灉涓嶈缃偅涔堥粯璁や负config/{AppName}
dbPath=
#濡傛灉涓嶈缃?閭ｄ箞浼氫紭鍏堟煡鎵綾onfig/{AppName}/{AppName}.db 濡傛灉涓嶅瓨鍦ㄩ偅涔堝皢浼氬垵濮嬪寲涓€涓猚onfig/{AppName}/{AppName}.db骞跺垵濮嬪寲鐩稿叧琛?
#濡傛灉璁剧疆 閭ｄ箞灏嗕細浣跨敤config/{AppName}/{dbFileName}.db
dbFileName=frog.db
