# nginx 配置
[run]
ports=17170,17171

# 目录配置
[path]
# 以下三个目录支持按机器盘符调整
webkit_driver_path={DRIVE}:/devtool/webkit_driver
webkit_data_path={DRIVE}:/devtool/webkit_data
webkit_download_path={DRIVE}:/devtool/webkit_download

[base]
# 如果未配置，则默认使用 config/{AppName}
dbPath=
# 如果未配置，则优先查找 config/{AppName}/{AppName}.db；
# 若文件不存在，会在该位置初始化一个新的 sqlite 数据库。
# 如果已配置，则使用 {dbPath}/{dbFileName}
dbFileName=frog.db

# 记忆库 sqlite 配置：
# 如果未配置，则记忆模块仅展示提示，不会初始化记忆库。
# 如果已配置，则使用 {memoryDbPath}/{memoryDbFileName}
memoryDbPath=
memoryDbFileName=memory.db
