#nginx配置
[run]
port=17170
wsPort=17171
ssePort=71721

#目录配置
[path]
webkit_node_path={PKG_PATH}/p_node
#这三个可以动态的固定目录
webkit_driver_path={DRIVE}:/devtool/webkit_driver
webkit_data_path={DRIVE}:/devtool/webkit_data
webkit_download_path={DRIVE}:/devtool/webkit_download